theme: jekyll-theme-hacker

plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
 
 defaults:
  - scope:
      path: ""
    values:
      layout: default
